In [4]:
import numpy as np
from skimage import feature

In [5]:
image = np.array([
    [10, 10, 10, 250, 250, 250],
    [10, 10, 10, 250, 250, 250],
    [10, 10, 10, 250, 250, 250],
    [10, 10, 10, 250, 250, 250],
    [10, 10, 10, 250, 250, 250]
])

In [6]:
image_gray = np.uint8(image) # convert image to grayscale

lbp = feature.local_binary_pattern(image_gray, 8, 1, method='uniform') # calculate Uniform Rotation Invariant LBP with neighborhood size 8 and radius 1

print(lbp)

[[3. 5. 6. 3. 5. 3.]
 [5. 8. 8. 5. 8. 5.]
 [5. 8. 8. 5. 8. 5.]
 [5. 8. 8. 5. 8. 5.]
 [3. 5. 6. 3. 5. 3.]]
