# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [16]:
import numpy as np

In [17]:
def create_matrix(n):
  matrix = np.random.randint(n, n+100, size=(n,n))
  return matrix

In [18]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
n = int(input())
matrix = create_matrix(n)
print(matrix)


[[ 68  80  77  90  16]
 [ 72  74  37  51 103]
 [ 12  17  95  29  37]
 [ 72  84  87  66  76]
 [ 45  18 104  95  84]]


In [19]:
def count_digits(matrix):
  digits = {}
  for i in range(10):
    digits[i] = 0
  for i in range(len(matrix)):
    for j in range(len(matrix[0])):
          digits[matrix[i][j] % 10] += 1
  
  return digits


In [20]:
"""
In this cell call the implemented function and print the result
"""
digits = count_digits(matrix)
print(digits)

{0: 2, 1: 1, 2: 3, 3: 1, 4: 4, 5: 3, 6: 3, 7: 5, 8: 2, 9: 1}


## Part B

In [21]:
def traverse_diameter(matrix, i, j):
  if i == 0 or j == n - 1:
    while i < n and j >= 0:
      print(matrix[i][j], end=" ")
      i += 1
      j -= 1
    i -= 1
    j += 1
  else:
    while i >= 0 and j < n:
      print(matrix[i][j], end=" ")
      i -= 1
      j += 1
    i += 1
    j -= 1
    
  return [i, j]

def traverse_matrix(matrix):
  i = 0
  j = 0
  print(matrix[i][j], end=" ")
  while i!=n-1 or j!=n-1:
    if i == 0 or i == n-1:
      j += 1
      if j == n:
        j -= 1
        i += 1
    else:
      i += 1
      if i == n:
        i -= 1
        j += 1
    [i, j] = traverse_diameter(matrix, i, j)
  

In [22]:
traverse_matrix(matrix)

[[ 68  80  77  90  16]
 [ 72  74  37  51 103]
 [ 12  17  95  29  37]
 [ 72  84  87  66  76]
 [ 45  18 104  95  84]]
68 80 72 12 74 77 90 37 17 72 45 84 95 51 16 103 29 87 18 104 66 37 76 95 84 