# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [24]:
import numpy as np

In [25]:
def create_matrix(n):
  matrix = np.random.randint(n, n+100, size=(n,n))
  return matrix

In [26]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
n = int(input())
matrix = create_matrix(n)
print(matrix)


[[ 84  48  61  11  61]
 [ 30  99  51  98  53]
 [ 89  57  72  17  47]
 [ 52  28  65 100  69]
 [ 15 104  64  31  32]]


In [27]:
def count_digits(matrix):
  digits = {}
  for i in range(10):
    digits[i] = 0
  for i in range(len(matrix)):
    for j in range(len(matrix[0])):
          digits[matrix[i][j] % 10] += 1
  
  return digits


In [28]:
"""
In this cell call the implemented function and print the result
"""
digits = count_digits(matrix)
print(digits)

{0: 2, 1: 5, 2: 3, 3: 1, 4: 3, 5: 2, 6: 0, 7: 3, 8: 3, 9: 3}


## Part B

In [29]:
def traverse_diameter(matrix, i, j):
  if i == 0 or j == n - 1:
    while i < n and j >= 0:
      print(matrix[i][j], end=" ")
      i += 1
      j -= 1
    i -= 1
    j += 1
  else:
    while i >= 0 and j < n:
      print(matrix[i][j], end=" ")
      i -= 1
      j += 1
    i += 1
    j -= 1
    
  return [i, j]

def traverse_matrix(matrix):
  i = 0
  j = 0
  print(matrix[i][j], end=" ")
  while i!=n-1 or j!=n-1:
    if i == 0 or i == n-1:
      j += 1
      if j == n:
        j -= 1
        i += 1
    else:
      i += 1
      if i == n:
        i -= 1
        j += 1
    [i, j] = traverse_diameter(matrix, i, j)
  

In [30]:
traverse_matrix(matrix)

84 48 30 89 99 61 11 51 57 52 15 28 72 98 61 53 17 65 104 64 100 47 69 31 32 