# Q3
*Work with Numpy*<br>
In this notebook you're going to work with the numpy library to solve the problems<br>
Please follow the instructions and hints provided for each cell

## Part A

In [24]:
import numpy as np

This code defines a function called `create_matrix` which takes an input `n`. The function generates a n by n matrix of random integers between `n` and `n+100` using the NumPy `randint` function. Finally, the function returns the generated matrix as output.

In [25]:
def create_matrix(n):
  matrix = np.random.randint(n, n+100, size=(n,n))
  return matrix

In [26]:
"""
In this cell you should get the input n and create the matrix by calling the function
Then print the matrix
"""
n = int(input())
matrix = create_matrix(n)
print(matrix)


[[ 84  48  61  11  61]
 [ 30  99  51  98  53]
 [ 89  57  72  17  47]
 [ 52  28  65 100  69]
 [ 15 104  64  31  32]]


This code defines a function called `count_digits` that takes a matrix as input. The function initializes an empty dictionary called `digits`. Then, the function iterates over the range of values from 0 to 9 using a for loop and initializes each key of the digits dictionary to 0.

The function then iterates over the rows and columns of the input matrix using nested for loops. It calculates the modulus of each element in the matrix by 10 and uses it as an index to increment the corresponding key value in the digits dictionary.

Finally, the function returns the updated digits dictionary with the count of each digit found in the input matrix.

In [27]:
def count_digits(matrix):
  digits = {}
  for i in range(10):
    digits[i] = 0
  for i in range(len(matrix)):
    for j in range(len(matrix[0])):
          digits[matrix[i][j] % 10] += 1
  
  return digits


In [28]:
"""
In this cell call the implemented function and print the result
"""
digits = count_digits(matrix)
print(digits)

{0: 2, 1: 5, 2: 3, 3: 1, 4: 3, 5: 2, 6: 0, 7: 3, 8: 3, 9: 3}


## Part B

This code defines two functions, `traverse_diameter` and `traverse_matrix`.

The `traverse_diameter` function takes in a `matrix`, `i`, and `j` as inputs. This function checks if `i` is equal to 0 or `j` is equal to `n-1` (where `n` is the number of rows/columns in the matrix). If this condition is true, it traverses the diagonal starting from the current `i` and `j` position in a downwards-leftwards direction until either `i` is equal to `n` or `j` is equal to -1. If the condition is false, it traverses the diagonal starting from the current `i` and `j` position in an upwards-rightwards direction until either `j` is equal to `n` or `i` is equal to -1. The function then returns a list of the updated `i` and `j` values.

The `traverse_matrix` function takes in a `matrix` as input. It initializes `i` and `j` to 0, and prints the element in the top-left corner of the matrix. The function then enters a while loop that continues until `i` is equal to `n-1` and `j` is equal to `n-1`, which represents the bottom-right corner of the matrix. The function checks if `i` is equal to 0 or `i` is equal to `n-1`. If this condition is true, it updates `j` to `j+1`, and if `j` is equal to `n`, it updates `j` to `j-1` and `i` to `i+1`. If the condition is false, it updates `i` to `i+1`, and if `i` is equal to `n`, it updates `i` to `i-1` and `j` to `j+1`. The function then calls the traverse_diameter function with the updated `i` and `j` values and repeats the process until the bottom-right corner is reached.

Overall, the `traverse_matrix` function traverses the matrix in a spiral-like pattern starting from the top-left corner and ending at the bottom-right corner, printing each element as it goes.

In [29]:
def traverse_diameter(matrix, i, j):
  if i == 0 or j == n - 1:
    while i < n and j >= 0:
      print(matrix[i][j], end=" ")
      i += 1
      j -= 1
    i -= 1
    j += 1
  else:
    while i >= 0 and j < n:
      print(matrix[i][j], end=" ")
      i -= 1
      j += 1
    i += 1
    j -= 1
    
  return [i, j]

def traverse_matrix(matrix):
  i = 0
  j = 0
  print(matrix[i][j], end=" ")
  while i!=n-1 or j!=n-1:
    if i == 0 or i == n-1:
      j += 1
      if j == n:
        j -= 1
        i += 1
    else:
      i += 1
      if i == n:
        i -= 1
        j += 1
    [i, j] = traverse_diameter(matrix, i, j)
  

In [30]:
traverse_matrix(matrix)

84 48 30 89 99 61 11 51 57 52 15 28 72 98 61 53 17 65 104 64 100 47 69 31 32 