# Q4

## Part A

This code performs matrix operations using NumPy library to solve a linear algebra problem.

The code starts by defining three matrices, A, B, and AT, where AT is the transpose of A.

Next, the code calculates AAT (A multiplied by its transpose), then uses the pinv() function from NumPy's linear algebra module to calculate the pseudo-inverse of AAT.

Afterward, the code calculates ATB (the product of the transpose of A and B) and multiplies it with the pseudo-inverse of AAT to get AATinvATB.

Finally, the code adds A to the result of the previous calculation to obtain AATinvATBA.

The resulting matrix AATinvATBA is printed out.

In summary, this code solves a linear system by multiplying, transposing, inverting, and adding matrices using NumPy.

In [3]:
"""
Please define the mentioned matrices and the operations

consider the bellow links:
https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

https://numpy.org/doc/stable/reference/generated/numpy.dot.html
"""

import numpy as np

# define the matrices
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1], [-1], [1]])
AT = np.transpose(A)   

# (A * AT)^-1 * AT * B + A

AAT = np.dot(A,AT)
AATinv = np.linalg.pinv(AAT)
ATB = np.dot(AT,B)
AATinvATB = np.dot(AATinv,ATB)
AATinvATBA = np.add(AATinvATB,A)
print(AATinvATBA)

[[2.92592593 3.92592593 4.92592593]
 [4.55555556 5.55555556 6.55555556]
 [6.18518519 7.18518519 8.18518519]]


## Part B

In [4]:
def window_sliding(A, B):

  """
  In this function you should implement the sliding window method

  Arguments:
    inputs:
      A: a matrix of 3*3 order for treating as the window
      B: a matrix of 5*5 order for treating as the input matrix
    outputs:
      res: resulting matrix of the sliding window 
  """

  # your code here
  res = np.zeros((3,3))
  for i in range(3):
    for j in range(3):
      res[i][j] = np.sum(np.multiply(A,B[i:i+3,j:j+3]))
  return res

In [5]:
A = np.array([[1, 1, 1], 
              [1, -9, 1], 
              [1, 1, 1]])
B = np.array([[1, 1, 1, 1, 1],
              [1, 2, 2, 2, 1], 
              [1, 2, 2, 2, 1],
              [1, 2, 2, 2, 1],
              [1, 1, 1, 1, 1]])
              
print(window_sliding(A, B))

[[-7. -5. -7.]
 [-5. -2. -5.]
 [-7. -5. -7.]]
